// SENSOR RELATED COMMANDS
#define READ_SENSOR_TEMPERATURE 0x01
#define DATA_SENSOR_TEMPERATURE 0x11

#define READ_SENSOR_HUMIDITY 0x02
#define DATA_SENSOR_HUMIDITY 0x12

#define READ_SENSOR_NO2 0x03
#define DATA_SENSOR_NO2 0x13

#define READ_SENSOR_CO 0x04
#define DATA_SENSOR_CO 0x14

#define READ_SENSOR_ALTITUDE 0x05
#define DATA_SENSOR_ALTITUDE 0x15

// RC RELATED COMMANDS
#define SET_CH1 0xF1
#define SET_CH2 0xF2
#define SET_CH3 0xF3
#define SET_CH4 0xF4
#define SET_CH5 0xF5
#define SET_CH6 0xF6
#define SET_CH7 0xF7
#define SET_CH8 0xF8

#define SET_MODE_ALTHOLD 0xE0
#define SET_MODE_LOITTER 0xE1
#define SET_MODE_AUTO    0xE2
#define SET_MODE_RTL     0xE3
#define SET_MODE_STB     0xE4
